apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews
  namespace: bookinfo
spec:
  gateway:
    - reviews
    - mesh
  hosts:
  - reviews
  - bookinfo.mkt.posanhanguera.com.br
  http:
  # Roteamento baseado em URI ou em Headers
  - match:  # curl http://reviews:9080/v1/reviews/0
    - uri:
        prefix: /v1/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: reviews
        subset: v1
  - match:  # curl -H "x-version: v2" http://reviews:9080/reviews/0
    - headers:
        x-version:
          exact: v2
    route:
    - destination:
        host: reviews
        subset: v2
  - match:  # curl http://reviews:9080/v1/reviews/0
    - uri:
        prefix: /v3/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: reviews
        subset: v3
  # Rota default (fallback) - distribuição 34/33/33
  # curl http://reviews:9080/reviews/0
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 34
    - destination:
        host: reviews
        subset: v2
      weight: 33
    - destination:
        host: reviews
        subset: v3
      weight: 33