apiVersion: argoproj.io/v1
kind: ApplicationSet
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        region: us-east-2

  template:
    metadata:
      name: "external-secrets-config-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default

      source:
        repoURL: 'https://github.com/org-sam/infra-gitops.git'
        targetRevision: HEAD
        path: infra-config/external-secrets
        helm:
          valuesObject:
            region: '{{region}}'

      destination:
        server: "{{server}}"
        namespace: external-secrets

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
