apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-gateway-config
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istio-gateway-config-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: hands-on
      source:
        repoURL: https://github.com/org-sam/infra-gitops.git
        targetRevision: main
        path: infra-config/istio-gateway
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
