apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karpenter-config
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        node_role: arn:aws:iam::703669458031:role/eks-node-initial-eks-node-group-20251205231303599500000003

  template:
    metadata:
      name: "karpenter-config-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/org-sam/infra-gitops.git'
        targetRevision: HEAD
        path: infra-base/config/karpenter
        
        helm:
          valuesObject:
            clusterName: '{{name}}'
            nodeRole: '{{node_role}}'

      destination:
        server: "{{server}}"
        namespace: karpenter
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true