apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karpenter-config
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        node_role_name: eks-node-initial-eks-node-group-20251230121757523200000002
        environment: dev

  template:
    metadata:
      name: "karpenter-config-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: hands-on
      source:
        repoURL: 'https://github.com/org-sam/infra-gitops.git'
        targetRevision: HEAD
        path: infra-config/karpenter/{{environment}}
        
        helm:
          valuesObject:
            clusterName: '{{name}}'
            nodeRole: '{{node_role_name}}'

      destination:
        server: "{{server}}"
        namespace: karpenter
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
